[build]
  command = "python manage.py collectstatic --noinput && python manage.py migrate"
  publish = "breast_ai/diagnostico/templates/diagnostico/"

[context.production]
  command = "python manage.py collectstatic --noinput && python manage.py migrate"

[context.deploy-preview]
  command = "python manage.py collectstatic --noinput && python manage.py migrate"
